import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ClerkAuthProvider } from "./ClerkAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const info: string = await new Promise((resolve) => {
    setTimeout(() => {
      resolve("This is a fake async function.");
    }, 1000);
  });

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <ThemeProvider>
        <div>RootLayout async info: {info}</div>
        <ClerkAuthProvider>{children}</ClerkAuthProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
